# Generated by Django 4.2.5 on 2023-09-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(default=None, max_length=128, null=True)),
                ('phone', models.CharField(default=None, max_length=10, null=True)),
                ('image_url', models.CharField(default=None, max_length=256, null=True)),
                ('points', models.IntegerField(default=0)),
                ('fcm_token', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('HOST_CARPOOL', 'HOST_CARPOOL'), ('LOG_BIKE_RIDE', 'LOG_BIKE_RIDE'), ('LOG_DELIVERY', 'LOG_DELIVERY'), ('LOG_FLIGHT', 'LOG_FLIGHT'), ('LOG_FOOD', 'LOG_FOOD'), ('LOG_POWER_BILL', 'LOG_POWER_BILL'), ('LOG_RECYCLING', 'LOG_RECYCLING'), ('LOG_WALK', 'LOG_WALK'), ('SEARCH_CARPOOL', 'SEARCH_CARPOOL')], default=None, max_length=64, null=True)),
                ('action_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default=None, max_length=64, null=True)),
                ('points_rewarded', models.IntegerField(default=0)),
                ('carbon_footprint', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=None, null=True)),
                ('calories', models.FloatField(default=None, null=True)),
                ('fabric', models.CharField(default=None, max_length=128, null=True)),
                ('energy', models.FloatField(default=None, null=True)),
                ('source_location', models.CharField(default=None, max_length=128, null=True)),
                ('destination_location', models.CharField(default=None, max_length=128, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
