# Generated by Django 4.2.5 on 2023-09-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('HOST_CARPOOL', 'HOST_CARPOOL'), ('LOG_BIKE_RIDE', 'LOG_BIKE_RIDE'), ('LOG_BUS', 'LOG_BUS'), ('LOG_CAR_EV', 'LOG_CAR_EV'), ('LOG_CAR_GAS', 'LOG_CAR_GAS'), ('LOG_DELIVERY', 'LOG_DELIVERY'), ('LOG_FLIGHT', 'LOG_FLIGHT'), ('LOG_FOOD', 'LOG_FOOD'), ('LOG_POWER_BILL', 'LOG_POWER_BILL'), ('LOG_RECYCLING', 'LOG_RECYCLING'), ('LOG_WALK', 'LOG_WALK'), ('SEARCH_CARPOOL', 'SEARCH_CARPOOL')], default=None, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CarpoolTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('source_location', models.CharField(default=None, max_length=128, null=True)),
                ('destination_location', models.CharField(default=None, max_length=128, null=True)),
                ('seats_available', models.IntegerField(default=1)),
                ('allowed_genders', models.CharField(default='all', max_length=64)),
                ('pool_uid_list', models.CharField(default=None, max_length=128, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
