# Generated by Django 4.2.5 on 2023-09-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_action_action_type_carpooltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooltask',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
